---
default_stages: [commit, push]
default_language_version:
  python: python3
  node: 18.6.0
minimum_pre_commit_version: '2.0.0'
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: Check if all hooks apply to the repository
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Run black (Python formatter)
        args: [--config=./pyproject.toml]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.256'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        name: Check that merge conflicts are not being committed
      - id: debug-statements
        name: Detect accidentally committed debug statements
      - id: check-builtin-literals
        name: Require literal syntax when initializing Python builtin types
      - id: end-of-file-fixer
        name: Make sure that there is an empty line at the end
        exclude: ^NOTICES$
      - id: mixed-line-ending
        name: Detect if mixed line ending is used (\r vs. \r\n)
      - id: check-executables-have-shebangs
        name: Check that executables have shebang
      - id: trailing-whitespace
        name: Remove trailing whitespace at end of line
        exclude: ^NOTICES$
      - id: pretty-format-json
        name: Format JSON files
        args:
          - --autofix
          - --no-sort-keys
          - --indent
          - "2"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint --strict
        types: [yaml]
  - repo: https://github.com/hadolint/hadolint
    rev: 'v2.12.0'
    hooks:
      - id: hadolint-docker
  - repo: local
    hooks:
      - id: yarn-format
        name: Run formatted for frontend code
        entry: ./dev.py js-format
        language: system
        files: ^frontend/src\/.+\.([jt]sx?|s?css)$
        require_serial: true
      - id: license-disclaimer
        name: Generate NOTICES
        language: system
        entry: bash -c "cd frontend; yarn license-disclaimer"
        files: '(package\.json|yarn\.lock)$'
        pass_filenames: false
